#!/usr/bin/env python
#-*- encoding:utf-8 -*-

import os
import sys
import shutil
import opencc
t2s = opencc.OpenCC('t2s.json')

def copy_normal(input, output):
    with open(input, "rb") as input_f:
        with open(output, "wb") as output_f:
            for line in input_f:
                line = line.decode("utf-8")
                i = line.index(" ")
                prefix = line[:i]
                suffix = line[i:]
                [name, name_t] = prefix.split("\t")
                # 如果出现相同尝试把第一个词语转为简体
                if name == name_t:
                    name = t2s.convert(name_t)
                # 写入简体
                output_f.write(("{}\t{}{}".format(name, name, suffix)).encode("utf-8"))
                # 有繁体与简体不同才写入
                if name != name_t:
                    output_f.write(("{}\t{}{}".format(name_t, name_t, suffix)).encode("utf-8"))

def main():
    input_dir = sys.argv[1]
    output_dir = sys.argv[2]
    for item in os.listdir(input_dir):
        item_path = os.path.join(input_dir, item)
        output_path = os.path.join(output_dir, item)
        if not item.endswith(".txt"):
            shutil.copyfile(item_path, output_path)
            continue
        print("copy_normal {} {}".format(item_path, output_path))
        copy_normal(item_path, output_path)

if __name__ == '__main__':
    exit(main())